Add support for multi-type unions.
godatadriven/pydantic-avro pull request #54
Opened 2022-12-21 21:13 UTC by enifsieus

This commit adds support for multi-union types, while preserving the generation of optional types for unions that are only null + a single type.

2023-01-04 21:58 UTC, enifsieus commented
Greetings - I'm wondering if this is a pull request that anyone is interested in discussing. Thanks!

2023-04-01 20:14 UTC, ffinfo commented
Sorry missed out some notifications on this project, will look into this. Sorry for the delay.

2023-04-01 20:15 UTC, ffinfo commented on pyproject.toml
> +version = "0.4.3"
please no updates to the versions, this will happen automatically on release

2023-04-18 09:51 UTC, ffinfo requested changes

2023-04-18 09:51 UTC, ffinfo commented on tests/test_from_avro.py
> +    assert "a_union: Union[None,int,str,ARecord]" in pydantic_code
This is incorrect, should be `a_union: Optional[int,str,ARecord] `

2023-04-18 09:51 UTC, ffinfo commented on tests/test_to_avro.py
> +    field: Union[None, str, int, NestedModel]
Should be Optional instead of union with None in there

2023-04-18 09:53 UTC, ffinfo commented on pyproject.toml
> +version = "0.4.3"
with with merge commit

2023-04-18 10:19 UTC, merged

2023-04-18 10:20 UTC, ffinfo commented
@enifsieus thanks for this, just merged this, will release this soon